---
language: bash
services: docker

env:
  - DOCKER_COMPOSE_VERSION=1.11.2

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y docker-engine

install:
  - sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

script:
  - docker-compose build

after_script:
  - docker ps
