---
language: bash
services: docker

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - cp .env.sample .env

script:
  - make up
  - ~/official-images/test/run.sh logs/elasticsearch

after_script:
  - docker ps
