---
language: bash
services: docker

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

script:
  - make up
  - ~/official-images/test/run.sh logs/elasticsearch

after_script:
  - docker ps
